### PR TITLE
Feat/formatting

### PR DESCRIPTION
**Pull request by merrygoat**
Some small alterations to formatting and imports

### CODE REVIEW

**Review by aplowman — COMMENTED** [review]
My intention with both `requirements.txt` and `environment.yml` is for them to be "development requirements" lists. E.g. for packages that may be required for testing. All the package "user" dependencies are in `setup.py` under `install_requires`. Do you know of a good reason to duplicate "user" dependencies in `requirements.txt`, @merrygoat ? If not, maybe we should rename `requirements.txt` to `requirements-dev.txt`.

**Comment by merrygoat** [comment]
Ah OK. I like having all the packages as a developer as then I can get code completion and type hints and even dive into the source if I want. Your choice 🙂

**Comment by aplowman** [comment]
I see, so your IDE uses the `requirements.txt` file. How about we rename `requirements.txt` to `requirements_dev.txt`, and keep the "user" packages that you added in it. I think you can then [set up IntelliJ to use that file](https://www.jetbrains.com/help/idea/managing-dependencies.html#configure-requirements)? Essentially, I don't want my "dev" packages (twine, autopep etc) to be requirements for a normal user installation. Renaming to `requirements_dev.txt` should make that clear I think.

**Comment by merrygoat** [comment]
Let's not complicate it - I think two requirements files would be a bit non-standard. Lets put it back and I can just get the IDE to ignore it.

**Comment by aplowman** [comment]
Having multiple `requirements.txt` files (and in particular one especially for development) [is](https://stackoverflow.com/questions/17803829/how-to-customize-a-requirements-txt-for-multiple-environments) [not](https://github.com/plotly/plotly.py/tree/master/packages/python/plotly) [unprecedented](https://github.com/matplotlib/matplotlib/tree/master/requirements/dev). Although, I actually mean we could just have one, `requirements_dev.txt` and it could be a one-stop-shop for any development packages that any regular contributors use (plus the "user" dependencies.)

So... I'm happy with doing that, or just putting it back to the way it was! 😄

**Comment by aplowman** [comment]
Thanks @merrygoat!

**Pull request merged**
